extends:
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-namespace':
    - off
    - allowDeclarations: true
      allowDefinitionFiles: true
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/explicit-module-boundary-types':
    - warn
    - allowArgumentsExplicitlyTypedAsAny: true

