openapi: 3.0.2
info:
  title: 'Example API'
  version: 1.0.0
  description: Lorem ipsum
tags:
  - name: Example
    description: Example endpoints
components:
  securitySchemes: !!import/merge
    - ./security-schemes.yml
  schemas: !!import/merge
    - ./schemas.yml

paths: !!import/merge
  - ./paths.yml
